### ISSUE TITLE
Dev builds of Unimus

### ISSUE THREAD

**Issue by tomaskir** [crocandr/docker-unimus#5]
Dev builds of Unimus are always available at:
https://unimus.net/download/dev-builds/download.html

Specifically the latest dev .jar is always available at:
https://unimus.net/download/dev-builds/Unimus.jar

These are updated periodically (sometimes daily), with the current dev version always available at https://unimus.net/download/dev-builds/Unimus.dev.version

While we don't advise to run these builds in production environments, it could be useful for users to have periodic access to dev builds for testing purposes.

**Comment by crocandr** [comment]
Thank you very much.

I created a dev branch and pushed a dev image to the docker hub with the latest dev version.
And created a wiki page too: https://github.com/crocandr/docker-unimus/wiki/download-specific-versions 

I will try to make something auto-build stuff for dev version because my GitHub-Docker Hub integration is not working :(

Thanks for the ticket and for the information too.

**Comment by crocandr** [comment]
I've found buildkite. I've created a scheduled task with that to build the dev version's container every night.
I hope it helps.
